language: node_js
node_js:
  - lts/*
script:
  - npm install -g yarn
  - yarn install
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: blog
  github-token: $GITHUB_TOKEN
  on:
    branch: master